### ISSUE TITLE
请教个小问题

### ISSUE THREAD

**Issue by Phelthas** [DaidoujiChen/DaiExpandCollectionView#3]
这个库写的真不错，我在学习你的源码和思路，有点问题请教一下  
1，`- (void)expandToLeftAtRow:(NSInteger)row selectIndexPath:(NSIndexPath *)selectedIndexPath isDefaultItem:(BOOL *)isDefaultItem frame:(CGRect *)frame` 这个方法中为什么用了`BOOL *`和`CGRect *`？这样做有什么好处or深意？         

2，库中`UIView+DaiExpandCollectionView`的干什么用的？

另外，我觉得把这个`DaiExpandCollectionViewFlowLayout`做成一个库要比做一个CollectionView做成库适用范围更大一些，毕竟能直接使用你的collectionView的场景还是不多

**Comment by DaidoujiChen** [comment]
Hello @Phelthas,

謝謝, 差點你就成為第 100 號星星者了!
關於第一個問題, 做一個很簡單的實驗, 如果寫成

```
- (void)viewDidLoad {
    [super viewDidLoad];
    BOOL input = YES;
    [self myMethod:input];
    NSLog(@"%d", input); // YES
}

- (void)myMethod:(BOOL)input {
    NSLog(@"%d", input); // YES
    input = NO;
    NSLog(@"%d", input); // NO
}
```

你會發現, 其實 `input` 最後的時候並沒有實際的被變動, 所以在 `- (void)expandToLeftAtRow:(NSInteger)row selectIndexPath:(NSIndexPath *)selectedIndexPath isDefaultItem:(BOOL *)isDefaultItem frame:(CGRect *)frame` 這個 method 裡面, 我想變動的值有兩個, 但是 return 的機會只有一次, 沒辦法讓 `isDefaultItem` 和 `frame` 都被變動, 因此用這種做法.

問題二, 主要是在修 https://github.com/DaidoujiChen/DaiExpandCollectionView/issues/2 這個問題.

最後一個部份我不太懂, 不過我最原始的目的, 只是說有一個朋友看到這個功能, 問我說該怎麼做, 我就做一個給他, 這樣而已, 哈哈.

**Comment by Phelthas** [comment]
@DaidoujiChen 
Thank you very much！（我本来也想等等再点星当第100个的，后来没忍住~哈哈）
原来是这么高端的用法~~学习了

最后一部分我是说，为了方便别人使用的话，单独把这个layout拿出来做一个库会更好一点，就像CSStickyHeaderFlowLayout一样

**Comment by DaidoujiChen** [comment]
Hello @Phelthas,

不會, 教學相長.

我是想說連 `UICollectionView` 一起包進去的話, 只要簡單的 implement 幾個 method, 就可以有一個還蠻好玩的效果, 靈活性雖然沒有這麼高, 不過使用的門檻也同時降低.

那我就 close 掉這個部分囉, 謝謝.
